language: node_js

node_js:
  - 7
  
env:
  global:
    - CHROME_BIN=chromium-browser
    - DISPLAY=:99.0

install:
  - npm install
  
script:
  - npm run build
  
cache:
  directories:
    - node_modules